FROM rust:1.89 AS builder

ARG SALT_ENCRYPTION_KEY
ARG SALT_ENCRYPTION_IV
ARG SCYLLA_CASSANDRA_PASSWORD
ENV SALT_ENCRYPTION_KEY $SALT_ENCRYPTION_KEY
ENV SALT_ENCRYPTION_IV $SALT_ENCRYPTION_IV
ENV SCYLLA_CASSANDRA_PASSWORD $SCYLLA_CASSANDRA_PASSWORD

LABEL maintainer=kickhead13<ana.alexandru.gabriel@proton.me>

COPY . .
RUN cargo test && cargo build --release

ENTRYPOINT ["./target/release/api"]
