FROM clux/muslrust:1.93.1-stable AS base
LABEL maintainer=kickhead13<ana.alexandru.gabriel@proton.me>
WORKDIR /build
ARG RUN_LINT
ARG SALT_ENCRYPTION_KEY
ARG SALT_ENCRYPTION_IV
ARG SCYLLA_CASSANDRA_PASSWORD
ARG RUN_UT
ARG OUTPUT=output

FROM base AS requirements
COPY --link --from=bare-repo . .
COPY --link Cargo* .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    cargo build --release --target x86_64-unknown-linux-musl

FROM requirements AS workspace
COPY --link src/ src/
COPY --link Cargo* .
RUN touch src/main.rs

FROM workspace AS linter-run
RUN mkdir ${OUTPUT}
RUN rustup component add clippy
RUN --mount=type=cache,target=/usr/local/cargo/registry \
   cargo clippy --release --target x86_64-unknown-linux-musl \
   -- -D warnings -A clippy::await_holding_lock \
   |& tee ${OUTPUT}/linter.log || ${OUTPUT}/LINTER_FAIL

FROM scratch AS linter
ARG OUTPUT=output
COPY --from=linter-run /build/${OUTPUT}/ .

FROM workspace AS ut-run
RUN mkdir ${OUTPUT}
RUN --mount=type=cache,target=/usr/local/cargo/registry \
   cargo test |& tee ${OUTPUT}/ut.log || touch ${OUTPUT}/UT_FAIL

FROM scratch AS ut
ARG OUTPUT=output
COPY --from=ut-run /build/${OUTPUT}/ .

FROM workspace AS builder
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    cargo build --release --target x86_64-unknown-linux-musl

FROM scratch AS runtime
COPY --link --from=builder /build/target/x86_64-unknown-linux-musl/release/api .
CMD ["/api"]
