name: Docker Compose CI

on:
  pull_request:
    branches: [ "main" ]

env:
  SALT_ENCRYPTION_KEY: ${{ secrets.SALT_ENCRYPTION_KEY }}
  SALT_ENCRYPTION_IV: ${{ secrets.SALT_ENCRYPTION_IV }}
  SCYLLA_CASSANDRA_PASSWORD: ${{ secrets.SCYLLA_CASSANDRA_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker compose -f compose.yaml build
