name: Rust CI Linter

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run linter
      run: cargo clippy --verbose -- -D warnings -A clippy::await_holding_lock

