name: API_CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SALT_ENCRYPTION_IV: ${{ secrets.SALT_ENCRYPTION_IV }}
  SALT_ENCRYPTION_KEY: ${{ secrets.SALT_ENCRYPTION_KEY }}
  SCYLLA_CASSANDRA_PASSWORD: ${{ secrets.SCYLLA_CASSANDRA_PASSWORD }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
