name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SALT_ENCRYPTION_KEY: ${{ env.SALT_ENCRYPTION_KEY }}
  SALT_ENCRYPTION_IV: ${{ env.SALT_ENCRYPTION_IV }}
  SCYLLA_CASSANDRA_PASSWORD: ${{ env.SCYLLA_CASSANDRA_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

